# -*- coding: utf-8 -*-
"""E-Commerce.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14e8mT8SF-S9SAVDgkr8xuG-0QoB40J7e
"""

class laptop:
  def __init__(self, name, brand, price, prossesor):
    self.__name = name
    self.__brand = brand
    self.__price = price
    self.__prossesor = prossesor
  def getName(self):
    return self.__name
  def getBrand(self):
    return self.__brand
  def getPrice(self):
    return self.__price
  def getProssesor(self):
    return self.__prossesor
  def output(self):
    return self.getName() + "      " + self.getBrand() + "      " + self.getPrice() + "    " + self.getProssesor()

class phone:
  def __init__(self, name, brand, price, battery):
    self.__name = name
    self.__brand = brand
    self.__price = price
    self.__battery = battery
  def getName(self):
    return self.__name
  def getBrand(self):
    return self.__brand
  def getPrice(self):
    return self.__price
  def getBattery(self):
    return self.__battery
  def output(self):
    return self.getName() + "      " + self.getBrand() + "      " + self.getPrice() + "    " + self.getBattery()



laptops = {}
phones = {}
basket = {}
idL = 100000
idP = 100
index = 1
while(True):  # kullanıcı çıkış yapıncaya kadar sistemin çalışması için sonsuz döngü ile çalışıyor.
  entry = int(input("Enter your prefer\n1 - Voler menu\n2 - Customer menu : \n0 - exit\n"))
  if (entry == 0):  # 2 boşluk bıraktım. Burada kullanıcıya hangi menüye girmek istediğine göre yönlendirme yapıyoruz.
    break
  elif (entry == 1):
    while(True):  # 4 boşluk
      first = int(input("1 - Notebook\n2 - Phone\n0 - exit\n"))  # 6 boşluk
      if (first == 0):  # 6 boşluk
        break;
      elif(first == 1):
        while(True):  # 8 boşluk
          Lfirst = int(input("1 - Add product\n2 - Remove Product\n0 - Exit\n"))
          if (Lfirst == 0):  
            break
          elif(Lfirst == 1):
            name = input("Enter product name : ")
            brand = input("Enter product brand : ")
            price = input("Enter product price : ")
            prossesor = input("Enter product prossesor model : ")
            idLaptop = brand[:2].lower() + "la" + str(idL)
            laptops[idLaptop] = laptop(name, brand, price,prossesor)  # kullanıcının girdiği değerler ile laptops sözlüğünde key -> ID value de -> laptop classından bir obje olacak şekilde değer ürettik. 
            idL += 1
          elif(Lfirst == 2):
            print("ID          name       brand         price     prossesor model")
            for key, value in laptops.items():  # laptops sözlüğündeki itemleri key ve value ye aktarıyoruz. value bir class olduğu için onun output methodunu çağırıyoruz.
              print(key, " ", value.output())
            rmvL = input("Enter the ID you want remove : ").lower()
            laptops.pop(rmvL)  # kullanıcıdan silmek isteiği ürünün ID sini aldık ve laptops sözlüğünden kaldırdık
            print("ID          name       brand         price     prossesor model")
            for key, value in laptops.items():  # laptops sözlüğünün son halini yeniden listeledik
              print(key, " ", value.output())
          else:
            print("you entered incorrectly. Please try again...")
      elif(first == 2):
        while(True):  # 8 boşluk
          Pfirst = int(input("1 - Add product\n2 - Remove Product\n0 - Exit\n"))
          if (Pfirst == 0):  # 10 boşluk
            break
          elif(Pfirst == 1):
            name = input("Enter product name : ")
            brand = input("Enter product brand : ")
            price = input("Enter product price : ")
            battery = input("Enter product battery model : ")
            idPhone = brand[:2].lower() + "ph" + str(idP)
            phones[idPhone] = phone(name, brand, price, battery) # kullanıcının girdiği değerler ile phones sözlüğünde key -> ID value de -> phone classından bir obje olacak şekilde değer ürettik. 
            idP += 1
          elif(Pfirst == 2):
            print("ID          name       brand         price     battery")
            for key, value in phones.items():  # phones sözlüğündeki itemleri key ve value ye aktarıyoruz. value bir class olduğu için onun output methodunu çağırıyoruz.
              print(key, " ", value.output())
            rmvP = input("Enter the ID you want remove : ").lower()
            phones.pop(rmvP)
            print("ID          name       brand         price     battery")
            for key, value in phones.items():
              print(key, " ", value.output())
          else:
            print("you entered incorrectly. Please try again...")
  elif(entry == 2):
    while(True):
      Cfirst = int(input("1 - add laptop to basket\n2 - add phone to basket\n3 - list basket\n4 - remove product\n0 - exit\n"))
      if(Cfirst == 0):
        break
      elif(Cfirst == 1):
        print("ID          name       brand         price     prossesor model")
        for key, value in laptops.items():
          print(key, " ", value.output())
        proID = input("Enter teh product ID you want to buy : ")
        if proID in laptops.keys():  # eğer kullanıcının girdiği ID laptops sözlüğünde varsa basket sözlüğüne ekliyor
          basket[proID] = laptops[proID]
          print("product added to your basket...")
        else:
          print("you entered incorrectly ID...")
      elif(Cfirst == 2):
        print("ID          name       brand         price     battery")
        for key, value in phones.items():
          print(key, " ", value.output())
        proID = input("Enter teh product ID you want to buy : ")
        if proID in phones.keys():
          basket[proID] = phones[proID]
          print("product added to your basket...")
        else:
          print("you entered incorrectly ID...")
      elif(Cfirst == 3):
        sum = 0
        for key, value in basket.items():
          print(key + " " +value.output())
          sum += int(value.getPrice())
        print("Number of product in basket -> ", len(basket))
        print("Total amount price of product in basket -> ", sum)
      elif(Cfirst == 4):
        sum = 0
        for key, value in basket.items():
          print(key + " " +value.output())
          sum += int(value.getPrice())
        print("Number of product in basket -> ", len(basket))
        print("Total amount price of product in basket -> ", sum)
        rID = input("Enter the product ID you want to remove : ")
        sum = 0  # sum değerini burada sıfırlamazsak altta listeyi tekrardan sıralarken kaldığı değerin üzerinden devam eder.
        if rID in basket.keys():
          basket.pop(rID)
          print("product removed from basket...")
        else:
          print("you entered incorrectly ID number...")
        for key, value in basket.items():
          print(key + " " +value.output())
          sum += int(value.getPrice())
        print("Number of product in basket -> ", len(basket))
        print("Total amount price of product in basket -> ", sum)


